default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kudos_development

test:
  <<: *default
  database: kudos_test

production:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL', '') %>
